stages:
  preparar:
    cmd: python src/preparar.py
    deps:
      - dados/dataset.csv
      - src/preparar.py
    outs:
      - dados/processado/

  treinar:
    cmd: python src/treinar.py
    deps:
      - dados/processado/
      - src/treinar.py
    outs:
      - modelos/modelo.joblib
    metrics:
      - metricas.json:
          cache: false
